version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: barbershop-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: barbershop
      MYSQL_USER: barbershop
      MYSQL_PASSWORD: barbershop
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sqlScript.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - barbershop-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Spring Boot Application
  barbershop-app:
    build: .
    container_name: barbershop-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/barbershop
      SPRING_DATASOURCE_USERNAME: barbershop
      SPRING_DATASOURCE_PASSWORD: barbershop
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_SHOW_SQL: true
    volumes:
      - uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - barbershop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local
  uploads:
    driver: local

networks:
  barbershop-network:
    driver: bridge
