name: Debug Permissions

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  pull-requests: write
  issues: write
  security-events: write
  actions: read

jobs:
  debug:
    name: Debug GitHub Token Permissions
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug GitHub Token
      run: |
        echo "GitHub Actor: ${{ github.actor }}"
        echo "GitHub Repository: ${{ github.repository }}"
        echo "GitHub Ref: ${{ github.ref }}"
        echo "GitHub Event Name: ${{ github.event_name }}"
        
        # Test basic API access
        echo "Testing GitHub API access..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }} | jq '.name, .full_name, .permissions'

    - name: Test Repository Access
      run: |
        echo "Testing repository read access..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/contents/README.md | jq '.name, .type'

    - name: Test Package Registry Access
      run: |
        echo "Testing package registry access..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/user/packages/container/${{ github.repository }} | jq '.name' || echo "No packages found or no access"

    - name: Test Release Access
      run: |
        echo "Testing release access..."
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/releases | jq '.[0].name' || echo "No releases found or no access"
